### PR TITLE
Pep8 Compliance

### PR DESCRIPTION
**Pull request by frdwrd**
I made my pep8 linter stop yelling at me. Tried to make styling consistent across files, and err on the side of not making changes.

Some comments are still too long. I wasn't sure how to address those, and I don't know that I was consistent.

I left a few warnings in docs/conf.py related to this line: `sys.path.insert(0, os.path.abspath('..'))` The warnings were `E402 module level import not at top of file`. I was unsure whether modifying the path affected those imports.

### CODE REVIEW

**Comment by frdwrd** [comment]
Broken build is because Master is currently broken.

**Comment by frdwrd** [comment]
Ah! Fixed it!

Tox.ini now ignores styling error W503, as PEP8 now officially recommends the opposite of what the linter checks for.

**Comment by steenzout** [comment]
looks good to me.

**Comment by steenzout** [comment]
looks good!

**Comment by frdwrd** [comment]
This is ready to be merged, btw

**Comment by super3** [comment]
ACK

**Pull request merged**
