### PR TITLE
fix 109

### LINKED ISSUE #109: Improve sharder to work with very large files
How the sharder hangs with very large file. (example 43 GB)
https://github.com/lakewik/storj-gui-client/issues/49

### PR DESCRIPTION
**Pull request by steenzout**
- `model.py`:
    - Token token attribute added
    - Token token keyword argument removed (obsolete)
    - ShardManager added docstring
    - ShardManager num_chunks attribute added
    - ShardManager suffix attribute added
    - ShardManager filesize property added
    - ShardManager tmp_path property added
    - ShardManager.get_optimal_shard_parameters(self) added docstring
    - ShardManager._make_shards(self) revamped (closes #109, #111 )
    - ShardManager.num_shards removed
    - ShardManager.determine_shard_size() fixed
    - ShardManager.get_optimal_shard_parameters() now returns a tuple (shard size, shard count)
- `cli.py`
    - fixed output of bucket get: #113

### CODE REVIEW

**Comment by steenzout** [comment]
#109 is fixed (for sure), #111 maybe, #112 is also fixed here.

**Comment by lakewik** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/lakewik/PycharmProjects/storjguibeta/4/storj-gui-client/UI/file_download.py", line 479, in get_shard_pointers
    skip=shard_index)
  File "/usr/local/lib/python2.7/dist-packages/storj/http.py", line 40, in decorator
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/storj/http.py", line 400, in file_pointers
    pull_token = self.token_create(bucket_id, operation='PULL')
  File "/usr/local/lib/python2.7/dist-packages/storj/http.py", line 40, in decorator
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/storj/http.py", line 740, in token_create
    json={'operation': operation}))
TypeError: __init__() got an unexpected keyword argument 'token'
```
while getting file pointers, only in this version

**Comment by steenzout** [comment]
@lakewik so you need the `token` or the `id` keyword argument?

**Comment by steenzout** [comment]
oh, I see... 1 sec...

**Comment by steenzout** [comment]
@lakewik fixed.

**Pull request merged**
