### PR TITLE
Fix shardmanager at upload

### PR DESCRIPTION
**Pull request by marcorosa**
I propose the following changes in class `ShardManager`:
- let the user define the number of shards and not the dimension of the shards (I think it is more "user friendly")
- if the user defines the number of shards (parameter `num_chunks`), use it! In fact, at the current version, we let the user specify the shard dimension but this parameter is not taken into consideration.
- Function `get_optimal_shard_parameters` returns the number of shards and their dimension, but the dimension is not used. So I propose to change it into `get_optimal_shard_number` since what we use is only the number of shards

### CODE REVIEW

**Comment by steenzout** [comment]
I just have a couple of questions:
1. If you change the number of shards that you'll use will that interfere with previous file downloads? from my little knowledge I'm assuming it's independent.
2. will this make the Python client behave even more differently that the official client?

**Comment by marcorosa** [comment]
This change doesn't affect file download since the `ShardManager` class (used for upload) is independent from the `ShardingTool` class (used for download).
A further step can be merging these 2 classes into one.

I've taken a look into the `storjlib` before this PR, and there seems to be no possibility for the user to decide the size or the number of shards.

**Comment by steenzout** [comment]
@marcorosa that's what I thought.

I'll still merge this PR after the build passes.

**Comment by marcorosa** [comment]
@steenzout test fixed according to previous commits

**Pull request merged**
