### PR TITLE
implement file upload

### PR DESCRIPTION
**Pull request by marcorosa**
I've implemented a first version of file upload. I've tested the upload of several files and it has always worked fine.
The code is based on the `storj-gui-client` I'm working on with @lakewik (https://github.com/lakewik/storj-gui-client)
There is still some work to do, some hints:
- [ ] Replace all the prints with a logger
- [ ] Delete shards from `/tmp`
- [ ] An overall refactoring
- [ ] Integrate it into the client class ?

How to use it:
```
from upload import Uploader
u = Uploader(email, password)
u.createNewUploadThread(bucket_id, file_path, tmp_path)
```

### CODE REVIEW

**Comment by steenzout** [comment]
@marcorosa the build failed. look [here](https://travis-ci.org/Storj/storj-python-sdk/jobs/225375838).

I think it's just a `lint` problem.
comments need to have a white space after the `#` character.

you can simulate the same problems using `tox -e py27 -- --ignore tests/integration`.

**Comment by steenzout** [comment]
@marcorosa PR to `develop` :)

**Comment by marcorosa** [comment]
I thought I selected `develop` branch.. my bad :sweat_smile:

**Comment by marcorosa** [comment]
@steenzout  do I need to fix all the pep8 errors?  I think that many of the lines generating errors are going to be edited or changed

**Comment by steenzout** [comment]
you only have 1 error now:

```
=================================== FAILURES ===================================
__________________________ PEP8-check(ignoring W503) ___________________________
[gw0] linux2 -- Python 2.7.9 /home/travis/build/Storj/storj-python-sdk/.tox/py27/bin/python2.7
/home/travis/build/Storj/storj-python-sdk/storj/uploader.py:32:120: E501 line too long (141 > 119 characters)
        FROM: <https://janusznawrat.wordpress.com/2015/04/08/wyliczanie-kryptograficznych-sum-kontrolnych-hmac-plikow-i-lancuchow-znakowych/>
                                                                                                                       ^
1 failed, 95 passed in 3.35 seconds
ERROR: InvocationError: '/home/travis/build/Storj/storj-python-sdk/.tox/py27/bin/py.test -q --basetemp=/home/travis/build/Storj/storj-python-sdk/.tox/py27/tmp --confcutdir=.. -n 1 --junitxml=tests/junit.xml --cov-report xml --cov storj --cov-report=html --cov-report term-missing --pep8 --ignore=tests/integration'
___________________________________ summary ____________________________________
ERROR:   py27: commands failed
```

**Comment by marcorosa** [comment]
Ok tests passed. we're ready :D

**Pull request merged**
