### PR TITLE
from core.lib.utils migrate simpleDecrypt and simpleEncrypt of data f…

### PR DESCRIPTION
**Pull request by BlackDuck888**
…or id_ecdsa

### CODE REVIEW

**Comment by steenzout** [comment]
```
__________________________ PEP8-check(ignoring W503) ___________________________
[gw0] linux2 -- Python 2.7.9 /home/travis/build/Storj/storj-python-sdk/.tox/py27/bin/python2.7
/home/travis/build/Storj/storj-python-sdk/storj/model.py:265:38: E261 at least two spaces before inline comment
        padding = 16 - len(data) % 16#
                                     ^
/home/travis/build/Storj/storj-python-sdk/storj/model.py:271:45: E226 missing whitespace around arithmetic operator
    def decrypt_node(self, hex_data, key='0'*32, iv='0'*16):
                                            ^
/home/travis/build/Storj/storj-python-sdk/storj/model.py:271:56: E226 missing whitespace around arithmetic operator
    def decrypt_node(self, hex_data, key='0'*32, iv='0'*16):
                                                       ^
/home/travis/build/Storj/storj-python-sdk/storj/model.py:276:41: E226 missing whitespace around arithmetic operator
    def encrypt_node(self, data, key='0'*32, iv='0'*16):
                                        ^
/home/travis/build/Storj/storj-python-sdk/storj/model.py:276:52: E226 missing whitespace around arithmetic operator
    def encrypt_node(self, data, key='0'*32, iv='0'*16):
```

**Comment by BlackDuck888** [comment]
i hope i got it now

**Comment by steenzout** [comment]
@BlackDuck888 you can test on your workstation by using `tox`. ;)

**Comment by BlackDuck888** [comment]
i will try it next time, step by step, so many new things, right now i am fighting with GitHub.

**Comment by BlackDuck888** [comment]
i close this pr, and will start from scratch, this will help me to understand how everything ist working

**Pull request closed without merging**
