### PR TITLE
tox

### PR DESCRIPTION
**Pull request by steenzout**
- use [tox](http://tox.readthedocs.io) to create virtualenvs and test code
- added python 3.5 classifier

with [tox](http://tox.readthedocs.io) parts of the Makefile don't make sense anymore but I'm leaving not to disrupt the way work is currently being done and let me people get used to this.

@frdwrd let me know what you think.

### CODE REVIEW

**Comment by super3** [comment]
:+1: from myself and @Miskerest. Merging.

**Comment by super3** [comment]
@steenzout Thanks for the pull, We are in the process of making this Python SDK great again. Are you in the Storj Slack Community Chat?

**Comment by steenzout** [comment]
@super3 I'm not on Storj Slack. how can I sign up?

**Comment by Miskerest** [comment]
@steenzout storjcommunity.slack.com

**Comment by steenzout** [comment]
thx, [got it](https://storj-inviter.herokuapp.com). ttyl...

**Pull request merged**
